theme: jekyll-theme-minimal
title: Genre Classification
description: comparing the effects of genre classification between different source separation techniques \n\nDaniel Thomas\nDaniel Perlovsky\nOliver Goodman
